- hosts: all
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx service
      service:
          name: nginx
          state: started
    - name: deploy index.html
      copy:
          src: index.html
          dest: /var/www/html/index.html